name: deepopg
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alsa-lib=1.2.8=h166bdaf_0
  - ampl-mp=3.1.0=h2cc385e_1006
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - antlr4-python3-runtime=4.11.1=py311h06a4308_0
  - aom=3.5.0=h27087fc_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - async-timeout=4.0.2=py311h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=22.1.0=py311h06a4308_0
  - blas=1.0=mkl
  - blinker=1.4=py311h06a4308_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py311h5eee18b_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.15.1=py311h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py311h06a4308_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=py311h06a4308_0
  - contourpy=1.1.0=py311h9547e67_0
  - cryptography=41.0.2=py311h22a60cf_0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=3.0.0=py311h5eee18b_0
  - data-science-types=0.2.23=pyhd8ed1ab_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - fftw=3.3.10=nompi_hc118613_108
  - filelock=3.9.0=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.40.0=py311h459d7ec_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py311h5eee18b_0
  - fsspec=2023.4.0=py311h06a4308_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gds-tools=1.4.0.31=0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.76.3=hfc55251_0
  - glib-tools=2.76.3=hfc55251_0
  - glpk=5.0=h445213a_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.7.8=hf3e180e_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.5.2=py311h06a4308_0
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.54.2=py311hcafe171_2
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.34=hd590300_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.14.0=nompi_hb72d44e_103
  - huggingface_hub=0.15.1=py311h06a4308_0
  - hydra-core=1.3.2=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.4=py311h06a4308_0
  - ijson=3.2.2=pyhd8ed1ab_0
  - imageio=2.31.1=pyh24c5eb1_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - iopath=0.1.9=pyhd8ed1ab_0
  - ipopt=3.14.12=hf9e1ecf_0
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - jinja2=3.1.2=py311h06a4308_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py311h4dd048b_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libclang=15.0.7=default_h7634d5b_2
  - libclang13=15.0.7=default_h9986a30_2
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcurl=8.2.1=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.17=h5eee18b_0
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.76.3=hebfc3b9_0
  - libglu=9.0.0=hf484d3e_1
  - libgpg-error=1.47=h71f35ed_0
  - libgrpc=1.54.2=hb20ce57_2
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - liblapacke=3.9.0=5_h92ddd45_netlib
  - libllvm15=15.0.7=hadd5161_1
  - libnghttp2=1.52.0=h2d74bed_1
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libogg=1.3.5=h27cfd23_1
  - libopencv=4.7.0=py311h7a0761e_1
  - libopus=1.3.1=h7b6447c_0
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=15.3=hbcd7760_1
  - libprotobuf=3.21.12=h3eb15da_0
  - libsndfile=1.2.0=hb75c966_0
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libsystemd0=253=h8c4010b_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.18.0=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.11.0=h295c915_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=1.5.0=h79f4944_0
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py311h06a4308_0
  - markdown-it-py=2.2.0=py311h06a4308_1
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib=3.7.1=py311h38be061_0
  - matplotlib-base=3.7.1=py311ha02d727_1
  - mdurl=0.1.0=py311h06a4308_0
  - metis=5.1.0=hf484d3e_4
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.6=py311ha02d727_1
  - mkl_random=1.2.2=py311ha02d727_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.31.3=hcb278e6_0
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.0.2=py311h5eee18b_0
  - mumps-include=5.2.1=ha770c72_11
  - mumps-seq=5.2.1=h2104b81_11
  - munkres=1.1.4=py_0
  - mypy=1.5.0=py311h459d7ec_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.0.33=hf1915f5_0
  - mysql-libs=8.0.33=hca2cd23_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.8.1=hc379101_1
  - networkx=3.1=py311h06a4308_0
  - nsight-compute=2022.3.0.22=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.25.2=py311h08b1b3b_0
  - numpy-base=1.25.2=py311hf175353_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - opencv=4.7.0=py311h38be061_1
  - openh264=2.3.1=hcb278e6_2
  - openssl=3.1.4=hd590300_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=23.1=py311h06a4308_0
  - pandas=2.0.3=py311h320fe9a_0
  - pandas-stubs=2.0.2.230605=pyhd8ed1ab_2
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pillow=9.4.0=py311h6a678d5_0
  - pip=23.1.2=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - ply=3.11=py311h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - portalocker=2.3.0=py311h06a4308_1
  - protobuf=4.21.12=py311hcafe171_0
  - psutil=5.9.0=py311h5eee18b_0
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - py-opencv=4.7.0=py311h781c19f_1
  - pycocotools=2.0.6=py311h4c7f6c3_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.10=py311h459d7ec_0
  - pygments=2.15.1=py311h06a4308_1
  - pyjwt=2.4.0=py311h06a4308_0
  - pyomo=6.6.1=py311hb755f60_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pyparsing=3.1.0=pyhd8ed1ab_0
  - pyqt=5.15.7=py311ha74522f_3
  - pyqt5-sip=12.11.0=py311hcafe171_3
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.4=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.0.1=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py311h06a4308_0
  - pyyaml=6.0=py311h5eee18b_1
  - qt-main=5.15.8=h5d23da1_6
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rich=13.4.2=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - safetensors=0.3.2=py311hb02cf49_0
  - scikit-learn=1.3.2=py311hc009520_1
  - scipy=1.11.1=py311h64a7726_0
  - scotch=6.0.9=hb2e6521_2
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - setuptools=68.0.0=py311h06a4308_0
  - sip=6.7.9=py311hb755f60_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - statsmodels=0.14.0=py311h1f0f07a_2
  - svt-av1=1.4.1=hcb278e6_0
  - sympy=1.12=pypyh9d50eac_103
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.13.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py311h52d8a92_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - timm=0.9.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py311h06a4308_0
  - torchaudio=2.0.2=py311_cu118
  - torchtriton=2.0.0=py311
  - torchvision=0.15.2=py311_cu118
  - tornado=6.3.2=py311h5eee18b_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - types-pytz=2022.4.0.0=py311h06a4308_1
  - types-requests=2.31.0.2=pyhd8ed1ab_0
  - types-urllib3=1.26.25.13=py311h06a4308_0
  - typing-extensions=4.7.1=py311h06a4308_0
  - typing_extensions=4.7.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - ultralytics=8.0.215=pyhf3ec037_0
  - unixodbc=2.3.11=h5eee18b_0
  - urllib3=1.26.16=py311h06a4308_0
  - werkzeug=2.2.3=py311h06a4308_0
  - wheel=0.38.4=py311h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.2=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py311h5eee18b_0
  - zipp=3.11.0=py311h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
