name: deepopg
channels:
  - nvidia/label/cuda-11.8.0
  - ibmdecisionoptimization
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20211102.0=h27087fc_1
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.4=py39hd1e30aa_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - ampl-mp=3.1.0=h2cc385e_1006
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - blinker=1.6.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - certifi=2023.5.7=py39h06a4308_0
  - cffi=1.15.1=py39he91dace_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.5=h3cb4718_0
  - coin-or-clp=1.17.7=h4e0f3ec_0
  - coin-or-osi=0.108.7=h3cb4718_0
  - coin-or-utils=2.11.6=h4e0f3ec_0
  - coinbonmin=1.8.9=hffa7344_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - cplex=22.1=py39_0
  - cryptography=41.0.1=py39hd4f0224_0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.35=py39h3d6467e_0
  - dataclasses=0.8=pyhc8e2a94_3
  - detectron2=0.6=cpu_py39h42bb6ba_6
  - filelock=3.12.2=pyhd8ed1ab_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.3.3=py39hb9d737c_0
  - future=0.18.3=pyhd8ed1ab_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gds-tools=1.4.0.31=0
  - giflib=5.2.1=h0b41bf4_3
  - glpk=5.0=h445213a_0
  - gmp=6.2.1=h58526e2_0
  - google-auth=2.20.0=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - grpcio=1.48.2=py39he1ff14a_1
  - hydra-core=1.3.2=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - ijson=3.2.1=pyhd8ed1ab_0
  - imageio=2.31.1=pyh24c5eb1_0
  - importlib-metadata=6.7.0=pyha770c72_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - iopath=0.1.9=pyhd8ed1ab_0
  - ipopt=3.14.10=hf60ba86_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h0b41bf4_3
  - kiwisolver=1.4.4=py39hf939315_1
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=17_linux64_openblas
  - libcblas=3.9.0=17_linux64_openblas
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=17_linux64_openblas
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.0=h6a678d5_2
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown=3.4.3=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py39hd1e30aa_0
  - matplotlib-base=3.4.3=py39h2fa2bec_2
  - mdurl=0.1.0=pyhd8ed1ab_0
  - metis=5.1.0=h58526e2_1006
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.4=py39h72bdee0_0
  - mumps-include=5.2.1=ha770c72_11
  - mumps-seq=5.2.1=h2104b81_11
  - ncurses=6.4=h6a678d5_0
  - networkx=3.1=pyhd8ed1ab_0
  - ninja=1.11.1=h924138e_0
  - nsight-compute=2022.3.0.22=0
  - numpy=1.25.0=py39h6183b62_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openssl=3.1.1=hd590300_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.2=py39h40cae4c_0
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.1.2=py39h06a4308_0
  - ply=3.11=py_1
  - portalocker=2.7.0=py39hf3d152e_0
  - protobuf=3.20.3=py39h227be39_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycocotools=2.0.6=py39h2ae25f5_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.9=py39hd1e30aa_0
  - pydot=1.2.4=py_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyjwt=2.7.0=pyhd8ed1ab_0
  - pyomo=6.6.1=py39h3d6467e_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h955ad1f_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=2.0.1=cpu_py39hab5cca8_0
  - pytz=2023.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_5
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rich=13.4.2=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scotch=6.0.9=h3858553_1
  - setuptools=67.8.0=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=pyh04b8f61_3
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tensorboard=2.13.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py39h079d5ae_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.14.1=cpu_py39hcda3413_0
  - tornado=6.3.2=py39hd1e30aa_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - typing-extensions=4.6.3=hd8ed1ab_0
  - typing_extensions=4.6.3=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - unixodbc=2.3.10=h583eb01_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - werkzeug=2.3.6=pyhd8ed1ab_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.2=py39hd1e30aa_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - opencv-python==4.7.0.72
